steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image-from-dockerfile'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image-to-gcr'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - '$TRIGGER_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
timeout: 9000s
