# CloudBuildでdocker buildし、Artifact Registryへプッシュする

steps:
  # docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '--no-cache', '-t',
      '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest',
      '-f', 'Dockerfile',
      '.',
    ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', '${_SERVICE_NAME}',
           '--image=${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest',
           '--region', '${_DEPLOY_REGION}', '--platform', 'managed',
           '--allow-unauthenticated',
           '--port=3000']

# Store images in Google Artifact Registry
images:
  - ${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest