steps:
  # STEP1: コンテナイメージをビルドする
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image-from-dockerfile'
    args:
      - 'build'
      - '-t'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  # STEP2: コンテナイメージをGAR(GoogleArtifactRegistry)にプッシュする
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image-to-gcr'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'

  # STEP3: Cloud Runにデプロイする
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - '$TRIGGER_NAME'
      - '--image'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
timeout: 9000s
